function include_path(inv)
    paths = ["/home/fs0/qijia/MATLAB/irt/nufft",...
    "/home/fs0/qijia/MATLAB/irt/utilities"...
    "/home/fs0/qijia/MATLAB/irt/systems"...
    genpath("/home/fs0/qijia/MATLAB/irt/mex"),...
    "/home/fs0/qijia/MATLAB/minTimeGradient/mex-interface"...
    "/home/fs0/qijia/MATLAB/encoding_transforms"...
    "/opt/fmrib/fsl/etc/matlab"...
    "/home/fs0/qijia/MATLAB/mapVBVD"...
    "/home/fs0/qijia/code/matlab"...
    genpath(".")];
    rmpath('/home/fs0/qijia/code/SimTraj/MChiewCAPRIARecon');
    for p = paths
        if nargin<1 || inv==0
            addpath(p)
        else
            rmpath(p)
        end
    end
end
    % "/home/fs0/qijia/code/spirit3d"...
    % genpath("/home/fs0/qijia/code/ESPIRiT")...